FROM python:latest

RUN mkdir /app
WORKDIR /app
COPY . /app/

RUN pip install -Ur requirements.txt
RUN python3 manage.py migrate

EXPOSE 8000

CMD [ "python3", "/app/manage.py", "runserver", "0.0.0.0:8000"]


