FROM python:latest

RUN mkdir /app
WORKDIR /app
COPY . /app/

RUN set -x && apt-get update && apt-get install -y nginx 
RUN mkdir data
RUN pip install -Ur requirements.txt
#RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
COPY uwsgi.ini /etc/uwsgi/
RUN python3 manage.py migrate --run-syncdb
RUN mkdir /var/log/uwsgi && chmod 1777 /var/log/uwsgi
RUN mkdir /var/run/uwsgi && chmod 1777 /var/run/uwsgi
EXPOSE 8000

CMD ["/app/start.sh"]

