apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
spec:
  storageClassName: aws-efs
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: fs-133c005a.efs.us-east-1.amazonaws.com
    path: "/"
